print('My name is "Rishabh". I love coding')
print('This is my first Program')
Value1 = input('Value of x: ' )
print ("Value1 is: ", Value1)
type(Value1)
Value2 = input('Value of Y: ' )
print ("value2 is: ", Value2)
type(Value2)
Value3 = input('Value of Z: ')
print("Value3 is: ", Value3)
type(Value3)

print('Hello! My name is Kruti')
print('"Hello I am a Candidate"')
a= float(234.56)
print(a)
b=int(34)
print(b)
c = complex(a+3j)
print(c)